### ISSUE TITLE
Received error: This plugin could not be found: serverless-runtime-babel

### ISSUE THREAD

**Issue by sohamnavadiya** [MoonMail/MoonMail#355]
```
root@moonmail:~/MoonMail/events# sls project init -c -n samplemoonmail
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: This plugin could not be found: serverless-runtime-babel
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:298:17)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:245:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:76:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:72:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

**Comment by rhinoandre** [comment]
Sorry on the delay, we are migrating our services and the focus of our devs is on that problem.

Please, install all the dependencies and try again.
You can read more about dependencies [here](https://github.com/MoonMail/MoonMail/blob/master/README.md#dependencies)
