### ISSUE TITLE
ServerlessError: Function Deployment Failed

### ISSUE THREAD

**Issue by caretapps** [MoonMail/MoonMail#446]
I am seeing the below error when I try to deploy functions

```
Serverless: Deploying the specified functions in "dev" to the following regions: us-west-2
Serverless: ------------------------
Serverless: Failed to deploy the following functions in "dev" to the following regions:
Serverless: us-west-2 ------------------------
Serverless:   createAutomationAction: undefined
Serverless:   updateAutomationAction: undefined
Serverless:   listAutomationActions: undefined
Serverless:   getAutomationAction: undefined
Serverless:   deleteAutomationAction: undefined
Serverless:   listSegmentsHttp: undefined
Serverless:   updateSegmentHttp: undefined
Serverless:   listSegmentMembersHttp: undefined
Serverless:   getSegmentHttp: undefined
Serverless:   createSegmentHttp: undefined
Serverless:   getCampaignReport: undefined
Serverless:   getAggregatedClicks: undefined
Serverless:   updateRecipient: undefined
Serverless:   getAggregatedOpens: undefined
Serverless:   unsubscribeRecipient: undefined
Serverless:   setUnsubscribeReason: undefined
Serverless:   searchRecipientsHttp: undefined
Serverless:   subscribeRecipient: undefined
Serverless:   listRecipientsHttp: undefined
Serverless:   getTotalRecipientsHttp: undefined
Serverless:   getRecipient: undefined
Serverless:   deleteRecipient: undefined
Serverless:   createRecipient: undefined
Serverless:   updateEmailList: undefined
Serverless:   bulkDeleteRecipients: undefined
Serverless:   sendTestConfirmationEmail: undefined
Serverless:   resetConfirmationEmailBody: undefined
Serverless:   listEmailLists: undefined
Serverless:   getEmailList: undefined
Serverless:   exportEmailList: undefined
Serverless:   createEmailList: undefined
Serverless:   deleteEmailList: undefined
Serverless:   linkClick: undefined
Serverless:   getLinks: undefined
Serverless:   emailOpen: undefined
Serverless:   updateTemplate: undefined
Serverless:   listTemplates: undefined
Serverless:   getTemplate: undefined
Serverless:   getBeeTokenProxy: undefined
Serverless:   duplicateTemplate: undefined
Serverless:   deleteTemplate: undefined
Serverless:   createTemplate: undefined
Serverless:   updateCampaign: undefined
Serverless:   unscheduleCampaign: undefined
Serverless:   sendTestEmail: undefined
Serverless:   sendTestCampaign: undefined
Serverless:   scheduleCampaign: undefined
Serverless:   listCampaigns: undefined
Serverless:   getCampaign: undefined
Serverless:   duplicateCampaign: undefined
Serverless:   deleteCampaign: undefined
Serverless:   updateAutomation: undefined
Serverless:   createCampaign: undefined
Serverless:   deliverCampaign: undefined
Serverless:   pauseAutomation: undefined
Serverless:   createAutomation: undefined
Serverless:   getAutomation: undefined
Serverless:   listAutomations: undefined
Serverless:   activateAutomation: undefined
/Users/amemon1/.config/yarn/global/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: Function Deployment Failed
    at new ServerlessError (/Users/amemon1/.config/yarn/global/node_modules/serverless/lib/Error.js:17:11)
    at FunctionDeploy.<anonymous> (/Users/amemon1/.config/yarn/global/node_modules/serverless/lib/actions/FunctionDeploy.js:126:19)
    at next (/Users/amemon1/.config/yarn/global/node_modules/rimraf/rimraf.js:83:7)
    at CB (/Users/amemon1/.config/yarn/global/node_modules/rimraf/rimraf.js:119:9)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at FunctionDeploy.functionDeploy (/Users/amemon1/.config/yarn/global/node_modules/serverless/lib/actions/FunctionDeploy.js:105:10)
From previous event:
    at /Users/amemon1/.config/yarn/global/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (<anonymous>)
    at /Users/amemon1/.config/yarn/global/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/Users/amemon1/.config/yarn/global/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/Users/amemon1/.config/yarn/global/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/Users/amemon1/.config/yarn/global/node_modules/serverless/lib/Serverless.js:398:38)
    at /Users/amemon1/.config/yarn/global/node_modules/serverless/bin/serverless:19:16
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Object.<anonymous> (/Users/amemon1/.config/yarn/global/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by woshea** [comment]
Basically MoonMail is broken for serverless and no action on this from the team. This appears to be an unmaintained project.

**Comment by rick-romero** [comment]
Anybody had any luck with that? Its probably some a version conflict/issue.

**Comment by coolrb** [comment]
Anybody succeeded in deploying using serverless?

**Comment by woshea** [comment]
We got stuck on this 5+ months ago. MoonMail at the time was, I believe,
working on an update for serverless. Since then no word. Would love to hear
from others.
